# Generated by Django 2.2.19 on 2023-02-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230216_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
